### ISSUE TITLE
Auto switch profiles based on AC/DC/PD

### ISSUE THREAD

**Issue by carverhaines** [CappyT/g14control#8]
Would be great to have a feature to set a default profile depending on your charging state, one for AC power adapter, one for DC battery, and one for USB-C Power delivery. Would need to be a user-defined variable in config.yaml.
Then have it auto-switch profiles depending on power state.

Example
```
app_name: "G14 Control"  # Name of the app, you can customize that as you wish!
notification_time: 3  # How long notifications will stay on the screen
check_power_every: 10  # Seconds in between checks to get the battery/ac status
default_ac_plan: "Performance"
default_dc_plan: "Silent (low-speed fan)"
default_pd_plan: "Silent (default fan speed)"
temp_dir: 'C:\temp\'
plans:
  - name: Silent (fanless)
    plan: silent
...
...
```
